(ld "arithmetic.lisp")
(ld "primes.lisp")
(ld "polynomials.lisp")
(ld "polynomial-thms.lisp")
(ld "fields.lisp")

; Acknowledgement: portions of this are inspired by generated code in
; Gihan's branch. (TODO: ask about provenance---which parts were generated,
; and with which tool?)

; Representations of finite fields: either prime or an extension
(defun ff-prime (p)
  (if (dm::primep p)
      (list :ff-prime p)
      :error[ff-prime][p-not-prime])
  )

(defun ff-ext (p modulus)
  (if (and (dm::primep p)
           (nonzeropolyp modulus))
      (list :ff-ext p modulus)
      :error[ff-ext][p-not-prime-or-modulus-not-nonzeropoly))

(defun ff-primep (F)
  (and (<= 2 (len F))
       (equal :ff-prime (first F))
       (dm::primep (second F))))

(defun ff-extp (F)
  (and (<= 3 (len F))
       (equal :ff-ext (first F))
       (dm::primep (second F))
       (nonzeropolyp (third F))))

(defun ffp (F) (or (ff-primep F) (ff-extp F)))

(defun ff-kind (F)
  (if (ffp F) (first F) :error[ff-kind][F-not-ff))

(defun ff-char (F)
  (if (ffp F) (second F) :error[ff-char][F-not-ff))

(defun ff-modulus (F)
  (if (ff-extp F) (third F) :error[ff-modulus][F-not-ff-ext))

(defun ff-order (F)
  (let ((char (ff-char F)))
    (case (ff-kind F)
      (:ff-prime char)
      (:ff-ext   (expt char (poly-deg (ff-modulus F)))))))

(defun ff-normed (F x)
  (let ((char (ff-char F)))
    (case (ff-kind F)
      (:ff-prime (mod x char))
      (:ff-ext   (poly-normed (mapmod char x))))))

;; Field operations

; Recognizer for field elements; do not worry about normalizing mod p
(defun ff-elemp (F x)
  (case (ff-kind F)
    (:ff-prime (integerp x))
    (:ff-ext   (polyp x))))

; NOTE! That the operations defined here do not take residue classes
; modulo the modulus of an extension finite field!
; We do reduce the *coefficients* modulo the characteristic, though.
; I don't think this affects the provability of the field axioms, 
(defun ff+ (F x y)
  (let ((char (ff-char F)))
    (case (ff-kind F)
      (:ff-prime (mod+ char x y))
      (:ff-ext   (polymod+ char x y)))))

(defun ff* (F x y)
  (let ((char (ff-char F)))
    (case (ff-kind F)
      (:ff-prime (mod* char x y))
      (:ff-ext   (polymod* char x y)))))

(defun ff0 (F)
  (case (ff-kind F)
    (:ff-prime 0)
    (:ff-ext   (zeropoly))))

(defun ff1 (F)
  (case (ff-kind F)
    (:ff-prime 1)
    (:ff-ext   (onepoly))))

(defun ff^ (F x n)
  (if (natp n)
      (if (zerop n)
          (ff1 F)
          (ff* F x (ff^ F x (nat-pred n))))
      :error[ff^][n-not-nat]))

(defun ff-neg (F x)
  (let ((char (ff-char F)))
    (case (ff-kind F)
      (:ff-prime (mod (- x) char))
      (:ff-ext   (polymod-neg char x)))))

; Because the multiplicative group of a finite field of order q
; is generated by a primitive q-th root of unity.
(defun ff/ (F x)
  (ff^ F x (- (ff-order F) 2)))

;; Field axioms
;  are satisfied:

(defthm ff+closed
  (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y))
           (ff-elemp F (ff+ F x y)))
  :hints
    (("Goal" :use (:instance polymod+-closed
                             (n (ff-char F))
                             (p x)
                             (q y)))))

(defthm ff*closed
  (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y))
           (ff-elemp F (ff* F x y)))
  :hints
    (("Goal" :use (:instance polymod*-closed
                             (n (ff-char F))
                             (p x)
                             (q y)))))

(defthmd ff+comm
  (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y))
           (equal (ff+ F x y) (ff+ F y x)))
  :hints
    (("Goal" :use (:instance polymod+-comm
                             (n (ff-char F))
                             (p x)
                             (q y)))))

; [WIP]
; (defthmd ff*comm
;   (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y))
;            (equal (ff* F x y) (ff* F y x)))
;   :hints
;     (("Goal" :use ?)))

; (defthmd ff+assoc (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y) (ff-elemp F z)) (equal (ff+ F x (ff+ F y z)) (ff+ F (ff+ F x y) z))))
; (defthmd ff*assoc (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y) (ff-elemp F z)) (equal (ff* F x (ff* F y z)) (ff* F (ff* F x y) z))))
; ;; Identity:
; (defthm ffelempff0 (implies (ffp F) (ff-elemp F (ff0 F))))
; (defthm ffelempFff1 (implies (ffp F) (ff-elemp F (ff1 F))))
; (defthm ff1ff0 (implies (ffp F) (not (equal (ff1 F) (ff0 F)))))
; (defthm ff0id (implies (and (ffp F) (ff-elemp F x)) (equal (ff+ F x (ff0 F)) x)))
; (defthm ff1id (implies (and (ffp F) (ff-elemp F x)) (equal (ff* F x (ff1 F)) x)))
; ;; Inverse:
; (defthm ffelempff- (implies (and (ffp F) (ff-elemp F x)) (ff-elemp F (ff- F x))))
; (defthm ffelempff/ (implies (and (ffp F) (ff-elemp F x) (not (equal x (ff0 F)))) (ff-elemp F (ff/ F x))))
; (defthm ff+inv (implies (and (ffp F) (ff-elemp F x)) (equal (ff+ F x (ff- F x)) (ff0 F))))
; (defthm ff*inv (implies (and (ffp F) (ff-elemp F x) (not (equal x (ff0 F)))) (equal (ff* F x (ff/ F x)) (ff1 F))))
; ;; Distributivity:
; (defthm ffdist (implies (and (ffp F) (ff-elemp F x) (ff-elemp F y) (ff-elemp F z)) (equal (ff* F x (ff+ F y z)) (ff+ F (ff* F x y) (ff* F x z)))))